site_name: Route Views Wish List
    
#
# nav: is for site routing (navigation).
# It will generally match the "docs/" directory structure, but can vary.
#
nav:
  - README.md
  - 🗳 Vote in GitHub!: https://github.com/routeviews/issues/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
  - Voting Guide: voting.md
  - Peer Request Guide: peer-request.md
  - New Collector Guide: new-collector.md

#
# We use a specific "theme" (and more) to make the site pretty!
#
theme:
  name: material
  logo: assets/RV-logo-new2-150px.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
extra:
  homepage: http://www.routeviews.org  # RV logo redirects to RV website
