name: Report a Bug
description: Report some buggy behavior you've seen related to the Route Views project.
labels: 
  - triage
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        > ℹ Before proceeding, it is wise to review [existing bug reports](https://github.com/routeviews/issues/issues?q=is%3Aissue+is%3Aopen+label%3Abug).
        > You might [vote](https://routeviews.github.io/issues/voting/) or comment on an existing issue rather than taking the time to fill this form.
  - type: textarea
    id: observed-behavior
    attributes:
      label: Observed Behavior
      description: What buggy behavior would you like to report?
      placeholder: Tell us what you are seeing!
      value: "A bug happened! 🐛😨"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: If the bug is fixed, what is the expected behavior?
      placeholder: Let us know what to strive for, and we'll do our best to make it reality!
  - type: textarea
    id: logs
    attributes:
      label: Relevant console output or logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  # SNIPPET: Code of Conduct
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://routeviews.github.io/issues/code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true