name: Report a Bug
description: Report some buggy behavior you've seen related to the Route Views project.
labels: 
  - triage
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        > ℹ Before reporting, please review [existing bug reports](https://github.com/routeviews/issues/issues?q=is%3Aissue+is%3Aopen+label%3Abug).
        > You might [vote](https://routeviews.github.io/issues/voting/) or comment on an existing issue rather than opening a new bug.
  - type: textarea
    id: observed-behavior
    attributes:
      label: Observed Behavior
      description: What buggy behavior would you like to report?
      placeholder: Tell us what you are seeing!
      value: "A bug happened! 🐛😨"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: If the bug is fixed, what is the expected behavior?
      placeholder: 
  - type: textarea
    id: logs
    attributes:
      label: Relevant console output or logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
