name: Request a Feature
description: Request an improvement to Route Views services.
labels: 
  - triage
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a feature request!

        > ℹ Before creating a request, please review [existing feature requests](https://github.com/routeviews/issues/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement).
        > You might [vote](https://routeviews.github.io/issues/voting/) or comment on an existing issue rather than creating a new request.

  - type: textarea
    id: details
    attributes:
      label: Enhancement Discussion
      placeholder: |
        Please discuss the enhancement you'd like to see.
        Some motivating questions:

        * What is the benefit of this enhancement? 
        * What challenges will you face if this feature is not implemented?
