name: Host a New Collector (draft)
description: Offer resources so Route Views can maintain a collector at your Internet Exchange (IX).
title: New Collector
labels: 
  - triage
  - collector
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for offering to host a Route Views collector!
        
        ℹ Please see the [New Collector Guide](https://routeviews.github.io/issues/new-collector/).
  - type: input
    id: fullname
    attributes:
      label: Full Name
      description: Your name, or the name of the entity you represent
    validations:
      required: true
  - type: input
    id: internet_exchanges
    attributes:
      label: IX(s)
      description: The Internet exchange(s) where the collector will connect
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location
      description: Coordinates where the collector is hosted (address accepted, but latitude and longitude preferred).
    validations:
      required: true
  - type: checkboxes
    id: new_collector_requirements
    attributes:
      label: System Requirements
      description: Review the system requirements outlined in the [New Collector Guide](https://routeviews.github.io/issues/new-collector/).
      options:
        - label: I have reviewed the system requirements, and am confident I can host a collector that meets the minimums.
          required: true
