name: Host a New Collector (draft)
description: Offer resources so Route Views can maintain a collector at your Internet Exchange (IX).
title: "New Collector"
labels: 
  - triage
  - collector
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for thinking about hosting a Route Views collector!
        
        ℹ Please see the [New Collector Guide](https://routeviews.github.io/issues/new-collector/).
  - type: input
    id: fullname
    attributes:
      label: Full Name
      description: Your name, or the name of the entity you represent
    validations:
      required: true
  - type: input
    id: internet_exchanges
    attributes:
      label: IX(s)
      description: The internet exchange(s) where the collector will connect
    validations:
      required: true
  - type: checkboxes
    id: new_collector_requirements
    attributes:
      label: System Requirements
      description: Review the System Requirements outlined in the [New Collector Guide](https://routeviews.github.io/issues/new-collector/).
      options:
        - label: I have reviewed the System Requirements, and am confident I can host a collector that meets the minimums.
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct (TODO)
      description: By submitting this issue, you agree to follow our [Code of Conduct (todo)](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
