name: Onboarding
description: Onboard a new Route Views maintainer! 🤓
title: "Onboarding <name here>"
labels: 
  - triage
  - enhancement
body:
  - type: input
    id: username
    attributes:
      label: Desired Username
      description: Linux username. Used as email as well, e.g. <username>@routeviews.org
  - type: textarea
    id: ssh_key
    attributes:
      label: SSH Key
      description: Public SSH key (RSA, >2048 bytes). Used to access Route Views infrastructure.
      render: shell
      value: Paste your RSA SSH public key here (or provide later in a issue-comment)...
  - type: markdown
    attributes:
      value: |
        What follows are the tasks required to fully enable a new Route Views (RV) maintainer.

        > ℹ When submitting this issue, you do not have to check ANY of the checkboxes below.
        > 
        > After you submit this issue, all the checkboxes below will be used to keep track of your onboarding process over the coming days.

        > This form is generated from the [routeviews/issues GitHub Repository](https://github.com/routeviews/issues).
        >
        > ℹ️ Tip: Want to suggest edits to this form?
        > Make your edits directly in GitHub.com web editors, then, "Create a new branch for this commit and start a pull request." 
  - type: checkboxes
    attributes:
      label: New Maintainer Initial Tasks
      description: |
        Tasks for you to complete before onboarding can begin.
      options:
        - label: Share Public SSH key (RSA, >2048 bytes)
  - type: checkboxes
    attributes:
      label: Existing Maintainer Tasks
      description: |
        Onboarding tasks to be completed by an existing Route Views Maintainer. (within days of submission)
      options:
        - label: Add to ["Route Views Maintainers" GitHub Team](https://github.com/orgs/routeviews/teams/maintainers/members?add=true).
        - label: Setup <username>@routeviews.org email account.
        - label: Provide access to [our Grafana instance](http://rvmonitor.routeviews.org:3000/).
        - label: Deploy public SSH Key to RV infrastructure (via Ansible).
        - label: Admit/ensure access to RV in PeeringDB.
        - label: Ensure access to RV Slack.
        - label: 'Provide access to the private Maintainer-only Slack channels. Today this includes: "peer requests" and "infrastructure".'
        - label: Share Route Views KeePass Master Password. (e.g., do this via RV Slack using [the "Secret Message" app](https://secretmessage.xyz/))
        - label: Help the new member complete their first 'peer request'! (e.g., schedule a time within the next work-week)
  - type: checkboxes
    attributes:
      label: New Maintainer Final Tasks
      description: |
        Onboarding tasks to for you to complete after an existing Route Views Maintainer completes their onboarding tasks.
      options:
        - label: Set up your mail client with your new Route Views email address. Refer to our [mail configuration documentation](https://github.com/routeviews/infra/blob/master/docs/contribute/mail_settings.md)
        - label: (BONUS) Set up the helpmail@routeviews.org email address also, giving you access to vast history of emails (credentials in [RV KeePass](https://github.com/routeviews/infra/blob/master/RouteViews.kdbx)).
        - label: Ensure access to [Route Views Slack](https://routeviewsworkspace.slack.com).
        - label: Review the [RV Maintainer Handbook (TODO update link to GH Pages)](https://github.com/routeviews/handbook).
        - label: Set up a PeeringDB account, and ['request Affiliation' with Route Views  (ASN 6447) on your PeeringDB profile page](https://www.peeringdb.com/profile)
        - label: Ensure login, and take a look through dashboards in [our Grafana instance](http://rvmonitor.routeviews.org:3000/).
        - label: Complete your first peer request! 😁 (with help from an existing maintainer)
