name: Report an Outage
description: Report that some Route Views Service is unexpectedly offline. 
labels: 
  - triage
  - outage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this outage report!

        > ℹ Before proceeding, it is wise to review [existing outages](https://github.com/routeviews/issues/issues?q=is%3Aopen+label%3Aoutage).
  - type: input
    id: host
    attributes:
      label: Effected Services/Hosts
      description: Fully Qualified Domain Name (FQDN) of the Route Views Services/Hosts that is/are down. (Whitespace-separated list is accepted)
      placeholder: archive.routeviews.org stream.routeviews.org
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: Please provide info about the outage that you think will help us.
  - type: textarea
    id: logs
    attributes:
      label: Console output or logs
      description: You may also paste relevant logs or console output here that may help. (This will be automatically formatted into code, so no need for backticks)
      render: shell
  # SNIPPET: Code of Conduct
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://routeviews.github.io/issues/  code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true