name: Report an Outage
description: Report that some Route Views service is unexpectedly offline. 
labels: 
  - triage
  - outage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit an outage report!

        > ℹ Before notifying us, please review [existing outages](https://github.com/routeviews/issues/issues?q=is%3Aopen+label%3Aoutage).
  - type: input
    id: host
    attributes:
      label: Effected Services/Hosts
      description: Fully Qualified Domain Name (FQDN) of the Route Views Services/Hosts that is/are down. (Whitespace-separated list is accepted)
      placeholder: archive.routeviews.org stream.routeviews.org
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: Please provide information about the outage that you think will help us.
  - type: textarea
    id: logs
    attributes:
      label: Console output or logs
      description: You may also paste relevant logs or console output here that may help. (This will be automatically formatted into code, so no need for backticks)
      render: shell
