name: Peering Request
description: Request a new BGP peering with one of our Route Views collectors.
title: Peering Request
labels: 
  - triage
  - "peer request"
body:
  - type: input
    id: fullname
    attributes:
      label: Full Name
      description: Or the name of the entity you represent
    validations:
      required: true
  - type: input
    id: asn
    attributes:
      label: ASN 
      description: Autonomous System Number (ASN)
    validations:
      required: true
  - type: checkboxes
    id: peeringdb_up_to_date
    attributes:
      label: PeeringDB Integration
      description: |
        Would you like to see **ALL EXCHANGES** where we can peer? [Visit peeringdb](https://www.peeringdb.com/net/3367)!
      options:
        - label: My PeeringDB Entries are current
          required: true
        - label: Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)
  - type: textarea
    id: ipaddrs
    attributes:
      label: Peer Address(es)
      description: >
        If you are not peering at **ALL EXCHANGES**, provide the IP address of the
        interface you'd like to peer with Route Views.
        List multiple addresses separated by whitespace characters (newlines, spaces, tabs, etc.)
  - type: checkboxes
    id: multihop
    attributes:
      label: Multihop
      description: >
        Is this a multihop peering session? If yes, make sure to set a 
        large TTL for this session! (*We configure `TTL=255`*)
      options:
        - label: Multihop Peering Request
