name: Peering Request
description: Request a new BGP peering with one of our Route Views collectors.
title: Peering Request
labels: 
  - triage
  - "peer request"
body:
  - type: input
    id: fullname
    attributes:
      label: Full Name
      description: Or the name of the entity you represent
    validations:
      required: true
  - type: input
    id: asn
    attributes:
      label: ASN 
      description: Your Autonomous System Number (ASN)
    validations:
      required: true
  - type: checkboxes
    id: peeringdb_up_to_date
    attributes:
      label: PeeringDB Integration
      description: |
        Wanna see **ALL EXCHANGES** where we can peer? Try out the [`routeviews` Python Package](https://pypi.org/project/routeviews/)!

            pip install routeviews
            routeviews-build-peer --asn <YOUR_ASN> --show-options
      options:
        - label: My PeeringDB Entries are current
          required: true
        - label: Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)
  - type: textarea
    id: ipaddrs
    attributes:
      label: Peer Address(es)
      description: >
        If not peering at **ALL EXCHANGES**, provide IP Addresses of the
        devices you'd like to peer with Route Views.
        List multiple addresses seperated by whitespace characters (newlines, spaces, tabs, etc.)
  - type: checkboxes
    id: multihop
    attributes:
      label: Multihop
      description: >
        Is this a multihop peering session? If yes, make sure to set a nice 
        long TTL for this session! (*We configure `TTL=255`*)
      options:
        - label: Multihop Peering Request
