name: Peering Request (draft)
description: Request a BGP peering with one of our Route Views collectors.
labels: 
  - "peer request"
body:
  - type: input
    id: fullname
    attributes:
      label: Your name, or the name of the entity you represent
    validations:
      required: true
  - type: input
    id: asn
    attributes:
      label: Your Autonomous System Number (ASN)
    validations:
      required: true
  - type: input
    id: ipaddrs
    attributes:
      label: The IP Address(es) of the devices you'd like to connect to. (Whitespace-seperated list is accepted)
    validations:
      required: true
  - type: input
    id: geolocation
    attributes:
      label: Where is this peer located?
      description: At least ISO Country Code. City, or rough address preferred.
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: peeringdb_up_to_date
    attributes:
      label: PeeringDB Entries Current? 
      description: Please ensure your PeeringDB entries are up to date before requesting peering. We rely heavily on integrations with PeeringDB to reduce overhead and improve operations.
      options:
        - label: My PeeringDB Entries are current
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct (TODO)
      description: By submitting this issue, you agree to follow our [Code of Conduct (todo)](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
