name: Replace/Upgrade a Collector
description: Request to replace/upgrade an existing Route Views collector.
title: Replace / Upgrade Collector
labels: 
  - triage
  - collector
  - enhancement
  - documentation
body:
  - type: markdown
    attributes:
      value: ℹ This form is intended for [@routeviews/maintainers](https://github.com/orgs/routeviews/teams/maintainers), to help track collector upgrades/replacements.
  - type: input
    id: collector
    attributes:
      label: Collector
      description: Which collector needs to be replaced/upgraded?
      placeholder: ex. isc.routeviews.org
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: >
        Why does this collector need to be replaced/upgraded? 
        Some examples: 
          * "Upgrade from deprecated operating system" 
          * "Major version upgrade for operating system" 
          * "Switching from physical host to virtual machine" 
          * "Hosting company requested this replacement/upgrade" 
    validations:
      required: true
