name: Publish Docs to GH Pages
on:
  push:
    branches:
      - main
jobs:
  publish:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

