name: Publish Docs to GH Pages
on:
  push:
    branches:
      - main
jobs:
  publish:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      # TODO, this doesn't seem to be deploying correctly today
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

